services:
  web:
    build: . # Baut das Image aus dem Dockerfile im aktuellen Verzeichnis
    container_name: medien-dl # Optional: Gibt dem Container einen festen Namen
    ports:
      - "5000:5000" # Mappt Port 5000 des Hosts auf Port 5000 des Containers
    volumes:
      # Mountet die History-Datei vom Host in den Container (persistent)
      - ./data/download_history.json:/app/download_history.json
      # Mountet die Statistik-Datei vom Host in den Container (persistent)
      - ./data/stats.json:/app/stats.json
      # Mountet den Download-Ordner vom Host in den Container (persistent)
      # Achtung: Stelle sicher, dass die Berechtigungen passen!
      - ./data/sc_downloads:/app/sc_downloads
    env_file:
      - .env # Lädt Umgebungsvariablen aus der .env-Datei im Host-System
    restart: unless-stopped # Startet den Container neu, außer er wurde manuell gestoppt